services:
  nginx:
    image: 'ghcr.io/lega0208/upd-new/nginx:latest'
    pull_policy: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  web:
    image: 'ghcr.io/lega0208/upd-new/web:latest'
    pull_policy: always
    container_name: web
    restart: unless-stopped
    ports:
      - '9000'
    secrets:
      - .env
      - secret.pem
      - aa_creds_pool.json
    environment:
      DOTENV_CONFIG_PATH: /run/secrets/.env
      AA_KEY_PATH: /run/secrets/secret.pem
      AA_KEY_POOL_PATH: /run/secrets/aa_creds_pool.json
      INSTANCE_ID: "prod-001"
      NODE_OPTIONS: "--max-old-space-size=6144"
    depends_on:
      - mongodb
      - redis

  db-updater:
    image: 'ghcr.io/lega0208/upd-new/db-updater:latest'
    pull_policy: always
    container_name: db-updater
    restart: unless-stopped
    ports:
      - '9001'
    secrets:
      - .env
      - secret.pem
      - service-account-credentials.json
    environment:
      DOTENV_CONFIG_PATH: /run/secrets/.env
      AA_KEY_PATH: /run/secrets/secret.pem
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/service-account-credentials.json
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0.5-jammy
    pull_policy: if_not_present
    container_name: upd_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true

  redis:
    image: redis:7.2.4
    pull_policy: if_not_present
    command: "redis-server --appendonly yes --maxmemory-policy noeviction"
    ports:
      - '6379'

volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /datadrive/db/data

secrets:
  .env:
    file: ../.env
  secret.pem:
    file: ../keys/secret.pem
  aa_creds_pool.json:
    file: ../keys/aa_creds_pool.json
  service-account-credentials.json:
    file: ../keys/service-account-credentials.json
