services:
  nginx:
    image: "upd_nginx"
    build:
      context: ../
      dockerfile: docker/performance_base/Dockerfile
      target: nginx-dev
    ports:
      - "8080:8080"
    depends_on:
      - web
    restart: unless-stopped
    container_name: upd_nginx

  web:
    image: "upd_web"
    container_name: upd_web
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/performance_base/Dockerfile
      target: web
    ports:
      - "9000"
    secrets:
      - .env
    environment:
      DOTENV_CONFIG_PATH: /run/secrets/.env
    depends_on:
      - mongodb
  db-updater:
    image: "upd_db-updater"
    container_name: upd_db-updater
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/performance_base/Dockerfile
      target: db-updater
    ports:
      - "9001"
    secrets:
      - .env
      - secret.pem
      - service-account-credentials.json
    environment:
      DOTENV_CONFIG_PATH: /run/secrets/.env
      AA_KEY_PATH: /run/secrets/secret.pem
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/service-account-credentials.json
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6
    container_name: upd_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true

volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "D:/docker-db"

secrets:
  .env:
    file: ../.env
  secret.pem:
    file: ../keys/secret.pem
  service-account-credentials.json:
    file: ../keys/service-account-credentials.json


